package com.spring.demo.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class DescInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.ID
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.CODE
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.NAME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.VERSION
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.COMPONENT
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.STATUS
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.CATEGORY
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.PROXIED_SERVICE
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String proxiedService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESC_INFO.INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.ID
     *
     * @return the value of DESC_INFO.ID
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.ID
     *
     * @param id the value for DESC_INFO.ID
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.CODE
     *
     * @return the value of DESC_INFO.CODE
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.CODE
     *
     * @param code the value for DESC_INFO.CODE
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.NAME
     *
     * @return the value of DESC_INFO.NAME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.NAME
     *
     * @param name the value for DESC_INFO.NAME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.VERSION
     *
     * @return the value of DESC_INFO.VERSION
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.VERSION
     *
     * @param version the value for DESC_INFO.VERSION
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.COMPONENT
     *
     * @return the value of DESC_INFO.COMPONENT
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.COMPONENT
     *
     * @param component the value for DESC_INFO.COMPONENT
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.STATUS
     *
     * @return the value of DESC_INFO.STATUS
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.STATUS
     *
     * @param status the value for DESC_INFO.STATUS
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.CREATE_TIME
     *
     * @return the value of DESC_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.CREATE_TIME
     *
     * @param createTime the value for DESC_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.UPDATE_TIME
     *
     * @return the value of DESC_INFO.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.UPDATE_TIME
     *
     * @param updateTime the value for DESC_INFO.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.CATEGORY
     *
     * @return the value of DESC_INFO.CATEGORY
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.CATEGORY
     *
     * @param category the value for DESC_INFO.CATEGORY
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.PROXIED_SERVICE
     *
     * @return the value of DESC_INFO.PROXIED_SERVICE
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getProxiedService() {
        return proxiedService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.PROXIED_SERVICE
     *
     * @param proxiedService the value for DESC_INFO.PROXIED_SERVICE
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setProxiedService(String proxiedService) {
        this.proxiedService = proxiedService == null ? null : proxiedService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESC_INFO.INFO
     *
     * @return the value of DESC_INFO.INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESC_INFO.INFO
     *
     * @param info the value for DESC_INFO.INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}