package com.spring.demo.mybatis.dao;

import com.spring.demo.mybatis.model.DescInfo;
import com.spring.demo.mybatis.model.DescInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DescInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int countByExample(DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int deleteByExample(DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int insert(DescInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int insertSelective(DescInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    List<DescInfo> selectByExampleWithBLOBs(DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    List<DescInfo> selectByExample(DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    DescInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") DescInfo record, @Param("example") DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") DescInfo record, @Param("example") DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int updateByExample(@Param("record") DescInfo record, @Param("example") DescInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int updateByPrimaryKeySelective(DescInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(DescInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESC_INFO
     *
     * @mbggenerated Mon Jun 20 18:56:18 CST 2016
     */
    int updateByPrimaryKey(DescInfo record);
}